### ISSUE TITLE
Convolution: center of kernel in the upper left corner

### ISSUE THREAD

**Issue by stefan-k** [rust-cv/ndarray-vision#11]
Hi,

thanks for this crate!
I tried to use the convolution and I noticed that the center of the kernel is not at the actual center but rather at the top left corner. This leads to a shift of the image to the upper left proportional to the size of the kernel. Furthermore some rows at the bottom and some columns on the right appear unprocessed (probably a problem with the boundary handling). I've attached two images to illustrate the problem: one without filter:
![phantom_nofilter](https://user-images.githubusercontent.com/553169/61710614-477feb80-ad52-11e9-853a-8c223431ddd4.png)
and the same with a 15x15 pixel `BoxLinearFilter`:
![phantom_filter](https://user-images.githubusercontent.com/553169/61710613-477feb80-ad52-11e9-8ddd-4b89a48785a9.png)

**Comment by xd009642** [comment]
So there's now a branch called better_conv that centres the kernels properly and adds two tests if you want to try that out. There's no padding implemented though

**Comment by xd009642** [comment]
I'm happy this works so I've just released 0.1.1 with this in. Let me know if you have any more issues (or open an issue or PR for padding :+1: )

**Comment by stefan-k** [comment]
Thanks for your quick response! I've just tired it and it works fine for my application!
