### ISSUE TITLE
docs.rs build failed for 0.2

### ISSUE THREAD

**Issue by quietlychris** [rust-cv/ndarray-vision#31]
I was just looking up some of the documentation for this crate on docs.rs, and it looks like the build has failed for the most recent version of 0.2. I think the crates.io build has worked, though, so not sure why it's happening. Just figured you might want to know!

**Comment by xd009642** [comment]
oh thanks I'll have a look at that before the next release... I suppose it could be switching the blas implementation for the dev profile :thinking:

**Comment by xd009642** [comment]
And I completely forgot about this until another issue was raised. #63  I'll keep open for this but I did the blas thing and hopefully they all build now (we'll see soon hopefully 0.5.1 just released)
