### ISSUE TITLE
docs failing for the latest release

### ISSUE THREAD

**Issue by CeNiEi** [rust-cv/ndarray-vision#63]
It seems that docs are failing for the latest release `0.5.0`, and for a lot of the previous releases as well. The last version for which the docs are visible is `0.1.1`

**Comment by xd009642** [comment]
Released 0.5.1 today which will hopefully fix the issue. I'll close it once i see the new docs.rs build go up :crossed_fingers:

**Comment by xd009642** [comment]
Yeah it's fixed :tada:
